// @generated by tools/sheets.py from sheets/*.json. Do not edit: change the sheet, then regenerate.
#![allow(dead_code, clippy::all)]

// ---- effects: Vanilla Elden Ring data rows the mashup reuses at runtime. Nothing here is shipped: the mod refers to these IDs in the player's own regulation. Names from soulsmods/Paramdex ER/Names (2026-03). 'mod' rows are effects the DLL implements itself.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EffectsParam { Bullet, SpEffectParam, EquipParamGoods, Mod }
#[derive(Debug)]
pub struct EffectsRow {
    pub id: &'static str,
    pub param: EffectsParam,
    pub row_id: i32,
    pub paramdex_name: &'static str,
}
pub const EFFECTS_NONE: EffectsRow = EffectsRow { id: "none", param: EffectsParam::Mod, row_id: 0, paramdex_name: "(no game row: effect done by the DLL)" };
pub const EFFECTS_GOODS_GIANTSFLAME_FIRE_POT: EffectsRow = EffectsRow { id: "goods_giantsflame_fire_pot", param: EffectsParam::EquipParamGoods, row_id: 302, paramdex_name: "Giantsflame Fire Pot" };
pub const EFFECTS_GOODS_ANCIENT_DRAGONS_LIGHTNING_STRIKE: EffectsRow = EffectsRow { id: "goods_ancient_dragons_lightning_strike", param: EffectsParam::EquipParamGoods, row_id: 6910, paramdex_name: "[Incantation] Ancient Dragons' Lightning Strike" };
pub const EFFECTS_GOODS_COMET_AZUR: EffectsRow = EffectsRow { id: "goods_comet_azur", param: EffectsParam::EquipParamGoods, row_id: 4200, paramdex_name: "[Sorcery] Comet Azur" };
pub const EFFECTS_GOODS_EXPLOSIVE_GHOSTFLAME: EffectsRow = EffectsRow { id: "goods_explosive_ghostflame", param: EffectsParam::EquipParamGoods, row_id: 5010, paramdex_name: "[Sorcery] Explosive Ghostflame" };
pub const EFFECTS_GOODS_REJECTION: EffectsRow = EffectsRow { id: "goods_rejection", param: EffectsParam::EquipParamGoods, row_id: 6400, paramdex_name: "[Incantation] Rejection" };
pub const EFFECTS_GOODS_BLESSINGS_BOON: EffectsRow = EffectsRow { id: "goods_blessings_boon", param: EffectsParam::EquipParamGoods, row_id: 6430, paramdex_name: "[Incantation] Blessing's Boon" };
pub const EFFECTS_GOODS_GREAT_HEAL: EffectsRow = EffectsRow { id: "goods_great_heal", param: EffectsParam::EquipParamGoods, row_id: 6422, paramdex_name: "[Incantation] Great Heal" };
pub const EFFECTS_GOODS_BOILED_CRAB: EffectsRow = EffectsRow { id: "goods_boiled_crab", param: EffectsParam::EquipParamGoods, row_id: 820, paramdex_name: "Boiled Crab" };
pub const EFFECTS_BULLET_GIANTSFLAME_FIRE_POT: EffectsRow = EffectsRow { id: "bullet_giantsflame_fire_pot", param: EffectsParam::Bullet, row_id: 10030200, paramdex_name: "Giantsflame Fire Pot" };
pub const EFFECTS_BULLET_ANCIENT_DRAGONS_LIGHTNING_STRIKE: EffectsRow = EffectsRow { id: "bullet_ancient_dragons_lightning_strike", param: EffectsParam::Bullet, row_id: 10691000, paramdex_name: "Ancient Dragons' Lightning Strike" };
pub const EFFECTS_BULLET_COMET_AZUR_CONSTANT: EffectsRow = EffectsRow { id: "bullet_comet_azur_constant", param: EffectsParam::Bullet, row_id: 10420002, paramdex_name: "Comet Azur - Constant Projectile" };
pub const EFFECTS_BULLET_EXPLOSIVE_GHOSTFLAME: EffectsRow = EffectsRow { id: "bullet_explosive_ghostflame", param: EffectsParam::Bullet, row_id: 10501000, paramdex_name: "Explosive Ghostflame" };
pub const EFFECTS_BULLET_REJECTION: EffectsRow = EffectsRow { id: "bullet_rejection", param: EffectsParam::Bullet, row_id: 10640000, paramdex_name: "Rejection" };
pub const EFFECTS_BULLET_BLESSINGS_BOON: EffectsRow = EffectsRow { id: "bullet_blessings_boon", param: EffectsParam::Bullet, row_id: 10643000, paramdex_name: "Blessing's Boon" };
pub const EFFECTS_BULLET_GREAT_HEAL: EffectsRow = EffectsRow { id: "bullet_great_heal", param: EffectsParam::Bullet, row_id: 10642200, paramdex_name: "Great Heal" };
pub const EFFECTS_SP_BOILED_CRAB: EffectsRow = EffectsRow { id: "sp_boiled_crab", param: EffectsParam::SpEffectParam, row_id: 500820, paramdex_name: "[Item] Boiled Crab" };
pub const EFFECTS_SP_HP_BURN: EffectsRow = EffectsRow { id: "sp_hp_burn", param: EffectsParam::SpEffectParam, row_id: 29001, paramdex_name: "NPC: HP Burn on Hit" };
pub static EFFECTS: &[&EffectsRow] = &[&EFFECTS_NONE, &EFFECTS_GOODS_GIANTSFLAME_FIRE_POT, &EFFECTS_GOODS_ANCIENT_DRAGONS_LIGHTNING_STRIKE, &EFFECTS_GOODS_COMET_AZUR, &EFFECTS_GOODS_EXPLOSIVE_GHOSTFLAME, &EFFECTS_GOODS_REJECTION, &EFFECTS_GOODS_BLESSINGS_BOON, &EFFECTS_GOODS_GREAT_HEAL, &EFFECTS_GOODS_BOILED_CRAB, &EFFECTS_BULLET_GIANTSFLAME_FIRE_POT, &EFFECTS_BULLET_ANCIENT_DRAGONS_LIGHTNING_STRIKE, &EFFECTS_BULLET_COMET_AZUR_CONSTANT, &EFFECTS_BULLET_EXPLOSIVE_GHOSTFLAME, &EFFECTS_BULLET_REJECTION, &EFFECTS_BULLET_BLESSINGS_BOON, &EFFECTS_BULLET_GREAT_HEAL, &EFFECTS_SP_BOILED_CRAB, &EFFECTS_SP_HP_BURN];

// ---- controls: Every key the mashup reads. 'vanilla' rows are Elden Ring's own bindings the design relies on; the mod reads but never rebinds them.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ControlsTrigger { Press, Hold, Vanilla }
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ControlsOwner { Mod, Vanilla }
#[derive(Debug)]
pub struct ControlsRow {
    pub id: &'static str,
    pub action: &'static str,
    pub key_name: &'static str,
    /// Windows virtual-key code
    pub vk_code: i32,
    pub trigger: ControlsTrigger,
    pub owner: ControlsOwner,
    /// what Elden Ring's default keyboard layout does with this key
    pub vanilla_conflict: &'static str,
}
pub const CONTROLS_TOGGLE_CAMERA: ControlsRow = ControlsRow { id: "toggle_camera", action: "Switch Dungeons view / Elden Ring view", key_name: "F5", vk_code: 116, trigger: ControlsTrigger::Press, owner: ControlsOwner::Mod, vanilla_conflict: "none known" };
pub const CONTROLS_ZOOM_IN: ControlsRow = ControlsRow { id: "zoom_in", action: "Camera closer", key_name: "=", vk_code: 187, trigger: ControlsTrigger::Hold, owner: ControlsOwner::Mod, vanilla_conflict: "none known" };
pub const CONTROLS_ZOOM_OUT: ControlsRow = ControlsRow { id: "zoom_out", action: "Camera further", key_name: "-", vk_code: 189, trigger: ControlsTrigger::Hold, owner: ControlsOwner::Mod, vanilla_conflict: "none known" };
pub const CONTROLS_ARTIFACT_1: ControlsRow = ControlsRow { id: "artifact_1", action: "Use hotbar slot 1", key_name: "1", vk_code: 49, trigger: ControlsTrigger::Press, owner: ControlsOwner::Mod, vanilla_conflict: "none known" };
pub const CONTROLS_ARTIFACT_2: ControlsRow = ControlsRow { id: "artifact_2", action: "Use hotbar slot 2", key_name: "2", vk_code: 50, trigger: ControlsTrigger::Press, owner: ControlsOwner::Mod, vanilla_conflict: "none known" };
pub const CONTROLS_ARTIFACT_3: ControlsRow = ControlsRow { id: "artifact_3", action: "Use hotbar slot 3", key_name: "3", vk_code: 51, trigger: ControlsTrigger::Press, owner: ControlsOwner::Mod, vanilla_conflict: "none known" };
pub const CONTROLS_ARTIFACT_MENU: ControlsRow = ControlsRow { id: "artifact_menu", action: "Open the artifact satchel to slot artifacts", key_name: "I", vk_code: 73, trigger: ControlsTrigger::Press, owner: ControlsOwner::Mod, vanilla_conflict: "none known" };
pub const CONTROLS_SATCHEL_NEXT: ControlsRow = ControlsRow { id: "satchel_next", action: "In the satchel: select the next artifact (then press 1, 2 or 3 to slot it)", key_name: "Tab", vk_code: 9, trigger: ControlsTrigger::Press, owner: ControlsOwner::Mod, vanilla_conflict: "none known" };
pub const CONTROLS_AIM_ATTACK: ControlsRow = ControlsRow { id: "aim_attack", action: "Right-hand attack; character turns toward the cursor first", key_name: "Left mouse", vk_code: 1, trigger: ControlsTrigger::Hold, owner: ControlsOwner::Vanilla, vanilla_conflict: "Elden Ring default: attack (right hand)" };
pub const CONTROLS_AIM_GUARD: ControlsRow = ControlsRow { id: "aim_guard", action: "Left-hand action / guard; character turns toward the cursor first", key_name: "Right mouse", vk_code: 2, trigger: ControlsTrigger::Hold, owner: ControlsOwner::Vanilla, vanilla_conflict: "Elden Ring default: guard / left-hand attack" };
pub const CONTROLS_ROLL: ControlsRow = ControlsRow { id: "roll", action: "Dodge-roll in the direction you move (screen-relative in Dungeons view)", key_name: "Space", vk_code: 32, trigger: ControlsTrigger::Vanilla, owner: ControlsOwner::Vanilla, vanilla_conflict: "Elden Ring default: backstep / dodge roll / dash" };
pub static CONTROLS: &[&ControlsRow] = &[&CONTROLS_TOGGLE_CAMERA, &CONTROLS_ZOOM_IN, &CONTROLS_ZOOM_OUT, &CONTROLS_ARTIFACT_1, &CONTROLS_ARTIFACT_2, &CONTROLS_ARTIFACT_3, &CONTROLS_ARTIFACT_MENU, &CONTROLS_SATCHEL_NEXT, &CONTROLS_AIM_ATTACK, &CONTROLS_AIM_GUARD, &CONTROLS_ROLL];

// ---- camera: Camera modes. One row per mode. The render camera (CSCamera.pers_cam_1) is overwritten every frame after CameraStep; the follow camera's yaw is pinned so stick/WASD movement is screen-relative.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CameraCeilingMode { None, Shorten }
#[derive(Debug)]
pub struct CameraRow {
    pub id: &'static str,
    pub label: &'static str,
    pub overrides_render: bool,
    /// angle below horizontal; Dungeons is steep
    pub pitch_deg: f32,
    /// fixed world yaw; 45 gives the Dungeons diagonal
    pub yaw_deg: f32,
    pub distance_m: f32,
    pub distance_min_m: f32,
    pub distance_max_m: f32,
    pub zoom_step_m: f32,
    pub fov_deg: f32,
    /// look-at point above the player's feet
    pub target_height_m: f32,
    /// 0 = snap, 1 = never moves
    pub follow_smoothing: f32,
    /// shorten = ray-cast from player to camera and pull in under ceilings (caves, catacombs, legacy dungeons)
    pub ceiling_mode: CameraCeilingMode,
    pub ceiling_margin_m: f32,
    pub toggle_control: &'static ControlsRow,
}
pub const CAMERA_DUNGEONS: CameraRow = CameraRow { id: "dungeons", label: "Dungeons view", overrides_render: true, pitch_deg: 55.0, yaw_deg: 45.0, distance_m: 16.0, distance_min_m: 9.0, distance_max_m: 26.0, zoom_step_m: 1.5, fov_deg: 40.0, target_height_m: 1.2, follow_smoothing: 0.15, ceiling_mode: CameraCeilingMode::Shorten, ceiling_margin_m: 0.6, toggle_control: &CONTROLS_TOGGLE_CAMERA };
pub const CAMERA_VANILLA: CameraRow = CameraRow { id: "vanilla", label: "Elden Ring view", overrides_render: false, pitch_deg: 0.0, yaw_deg: 0.0, distance_m: 0.0, distance_min_m: 0.0, distance_max_m: 0.0, zoom_step_m: 0.0, fov_deg: 0.0, target_height_m: 0.0, follow_smoothing: 0.0, ceiling_mode: CameraCeilingMode::None, ceiling_margin_m: 0.0, toggle_control: &CONTROLS_TOGGLE_CAMERA };
pub static CAMERA: &[&CameraRow] = &[&CAMERA_DUNGEONS, &CAMERA_VANILLA];

// ---- rarity: Dungeons-style rarity tiers for every drop. Colour is the loot beam and the toast text.
#[derive(Debug)]
pub struct RarityRow {
    pub id: &'static str,
    pub label: &'static str,
    pub tier: i32,
    pub color_r: f32,
    pub color_g: f32,
    pub color_b: f32,
    pub beam_height_m: f32,
    pub beam_radius_m: f32,
    /// level of the enchantment an enchant drop of this rarity gives
    pub enchant_level: i32,
    pub roll_weight: i32,
}
pub const RARITY_COMMON: RarityRow = RarityRow { id: "common", label: "Common", tier: 1, color_r: 0.92, color_g: 0.92, color_b: 0.92, beam_height_m: 6.0, beam_radius_m: 0.12, enchant_level: 1, roll_weight: 70 };
pub const RARITY_RARE: RarityRow = RarityRow { id: "rare", label: "Rare", tier: 2, color_r: 0.3, color_g: 0.72, color_b: 1.0, beam_height_m: 9.0, beam_radius_m: 0.16, enchant_level: 2, roll_weight: 25 };
pub const RARITY_UNIQUE: RarityRow = RarityRow { id: "unique", label: "Unique", tier: 3, color_r: 1.0, color_g: 0.68, color_b: 0.12, beam_height_m: 14.0, beam_radius_m: 0.22, enchant_level: 3, roll_weight: 5 };
pub static RARITY: &[&RarityRow] = &[&RARITY_COMMON, &RARITY_RARE, &RARITY_UNIQUE];

// ---- artifacts: The artifact hotbar: Minecraft Dungeons artifacts built from Elden Ring items. Three hotbar slots (controls artifact_1..3). Artifacts drop as loot and are slotted from the satchel (controls artifact_menu). The Elden Ring item's name is read from the game's own text at runtime and shown next to the Dungeons name.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ArtifactsKind { BulletTowardCursor, BulletAtCursor, BulletAtSelf, ChannelTowardCursor, SpeffectSelf }
#[derive(Debug)]
pub struct ArtifactsRow {
    pub id: &'static str,
    pub dungeons_name: &'static str,
    /// EquipParamGoods row the artifact is made from (name shown in the hotbar)
    pub er_item: &'static EffectsRow,
    pub kind: ArtifactsKind,
    pub effect: &'static EffectsRow,
    pub cooldown_s: f32,
    pub fp_cost: i32,
    /// channel only: FP drained per second while held (Dungeons' souls)
    pub fp_per_s: i32,
    pub channel_interval_s: f32,
    pub drop_weight: i32,
    /// how it behaves in Seamless Co-op
    pub coop: &'static str,
    pub description: &'static str,
}
pub const ARTIFACTS_FIREWORKS_ARROW: ArtifactsRow = ArtifactsRow { id: "fireworks_arrow", dungeons_name: "Fireworks Arrow", er_item: &EFFECTS_GOODS_GIANTSFLAME_FIRE_POT, kind: ArtifactsKind::BulletTowardCursor, effect: &EFFECTS_BULLET_GIANTSFLAME_FIRE_POT, cooldown_s: 7.0, fp_cost: 0, fp_per_s: 0, channel_interval_s: 0.0, drop_weight: 14, coop: "engine bullet owned by the player; partners should see it as they see thrown pots", description: "Hurl an exploding Giantsflame pot where you point." };
pub const ARTIFACTS_LIGHTNING_ROD: ArtifactsRow = ArtifactsRow { id: "lightning_rod", dungeons_name: "Lightning Rod", er_item: &EFFECTS_GOODS_ANCIENT_DRAGONS_LIGHTNING_STRIKE, kind: ArtifactsKind::BulletAtCursor, effect: &EFFECTS_BULLET_ANCIENT_DRAGONS_LIGHTNING_STRIKE, cooldown_s: 10.0, fp_cost: 10, fp_per_s: 0, channel_interval_s: 0.0, drop_weight: 12, coop: "engine bullet owned by the player", description: "Call down Ancient Dragon lightning on the cursor." };
pub const ARTIFACTS_CORRUPTED_BEACON: ArtifactsRow = ArtifactsRow { id: "corrupted_beacon", dungeons_name: "Corrupted Beacon", er_item: &EFFECTS_GOODS_COMET_AZUR, kind: ArtifactsKind::ChannelTowardCursor, effect: &EFFECTS_BULLET_COMET_AZUR_CONSTANT, cooldown_s: 1.0, fp_cost: 0, fp_per_s: 12, channel_interval_s: 0.1, drop_weight: 6, coop: "engine bullets owned by the player, many per second", description: "Hold to fire a Comet Azur beam toward the cursor. Drains FP like souls." };
pub const ARTIFACTS_HARVESTER: ArtifactsRow = ArtifactsRow { id: "harvester", dungeons_name: "Harvester", er_item: &EFFECTS_GOODS_EXPLOSIVE_GHOSTFLAME, kind: ArtifactsKind::BulletAtSelf, effect: &EFFECTS_BULLET_EXPLOSIVE_GHOSTFLAME, cooldown_s: 6.0, fp_cost: 15, fp_per_s: 0, channel_interval_s: 0.0, drop_weight: 12, coop: "engine bullet owned by the player", description: "Burst of ghostflame all around you." };
pub const ARTIFACTS_WIND_HORN: ArtifactsRow = ArtifactsRow { id: "wind_horn", dungeons_name: "Wind Horn", er_item: &EFFECTS_GOODS_REJECTION, kind: ArtifactsKind::BulletAtSelf, effect: &EFFECTS_BULLET_REJECTION, cooldown_s: 12.0, fp_cost: 0, fp_per_s: 0, channel_interval_s: 0.0, drop_weight: 14, coop: "engine bullet owned by the player", description: "Blast enemies away from you." };
pub const ARTIFACTS_TOTEM_OF_REGENERATION: ArtifactsRow = ArtifactsRow { id: "totem_of_regeneration", dungeons_name: "Totem of Regeneration", er_item: &EFFECTS_GOODS_BLESSINGS_BOON, kind: ArtifactsKind::BulletAtSelf, effect: &EFFECTS_BULLET_BLESSINGS_BOON, cooldown_s: 20.0, fp_cost: 0, fp_per_s: 0, channel_interval_s: 0.0, drop_weight: 12, coop: "Blessing's Boon's own area heal should reach partners in range", description: "Heal yourself and nearby friends over time." };
pub const ARTIFACTS_SOUL_HEALER: ArtifactsRow = ArtifactsRow { id: "soul_healer", dungeons_name: "Soul Healer", er_item: &EFFECTS_GOODS_GREAT_HEAL, kind: ArtifactsKind::BulletAtSelf, effect: &EFFECTS_BULLET_GREAT_HEAL, cooldown_s: 4.0, fp_cost: 25, fp_per_s: 0, channel_interval_s: 0.0, drop_weight: 12, coop: "Great Heal's own area heal should reach partners in range", description: "Spend FP to heal yourself and nearby friends." };
pub const ARTIFACTS_IRON_HIDE_AMULET: ArtifactsRow = ArtifactsRow { id: "iron_hide_amulet", dungeons_name: "Iron Hide Amulet", er_item: &EFFECTS_GOODS_BOILED_CRAB, kind: ArtifactsKind::SpeffectSelf, effect: &EFFECTS_SP_BOILED_CRAB, cooldown_s: 30.0, fp_cost: 0, fp_per_s: 0, channel_interval_s: 0.0, drop_weight: 18, coop: "buff applied to yourself only", description: "Harden your skin like a Boiled Crab: less damage taken for a while." };
pub static ARTIFACTS: &[&ArtifactsRow] = &[&ARTIFACTS_FIREWORKS_ARROW, &ARTIFACTS_LIGHTNING_ROD, &ARTIFACTS_CORRUPTED_BEACON, &ARTIFACTS_HARVESTER, &ARTIFACTS_WIND_HORN, &ARTIFACTS_TOTEM_OF_REGENERATION, &ARTIFACTS_SOUL_HEALER, &ARTIFACTS_IRON_HIDE_AMULET];

// ---- enchantments: Dungeons enchantments on Elden Ring gear. An enchant drop adds one enchantment (level = drop rarity) to the weapon in your active right-hand slot or to your chest armour. Each piece holds up to 3; a duplicate keeps the higher level; a full piece replaces its lowest. Stored per character in the mod's own save file, keyed by the item's inventory handle. Damage effects are the DLL's own: it watches enemy HP drops caused by the local player and applies the extra.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EnchantmentsSlot { Weapon, Armor }
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EnchantmentsTrigger { OnHit, OnKill, OnHurt, EveryNthHit, OnArtifactUse, Passive }
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EnchantmentsValueUnit { PctHitDamage, PctPlayerMaxHp, PctCooldown, None }
#[derive(Debug)]
pub struct EnchantmentsRow {
    pub id: &'static str,
    pub dungeons_name: &'static str,
    pub slot: EnchantmentsSlot,
    pub trigger: EnchantmentsTrigger,
    /// every_nth_hit only
    pub nth: i32,
    /// 100 = always
    pub chance_pct_per_level: f32,
    pub value_per_level: f32,
    pub value_unit: EnchantmentsValueUnit,
    /// area enchantments only, 0 otherwise
    pub radius_m: f32,
    /// condition on the target's HP; 100 = any
    pub target_hp_below_pct: f32,
    pub game_effect: &'static EffectsRow,
    pub drop_weight: i32,
    pub coop: &'static str,
    pub description: &'static str,
}
pub const ENCHANTMENTS_SHARPNESS: EnchantmentsRow = EnchantmentsRow { id: "sharpness", dungeons_name: "Sharpness", slot: EnchantmentsSlot::Weapon, trigger: EnchantmentsTrigger::OnHit, nth: 0, chance_pct_per_level: 100.0, value_per_level: 8.0, value_unit: EnchantmentsValueUnit::PctHitDamage, radius_m: 0.0, target_hp_below_pct: 100.0, game_effect: &EFFECTS_NONE, drop_weight: 16, coop: "extra damage written to the enemy's HP by the hitting player's DLL", description: "+8% damage per level." };
pub const ENCHANTMENTS_COMMITTED: EnchantmentsRow = EnchantmentsRow { id: "committed", dungeons_name: "Committed", slot: EnchantmentsSlot::Weapon, trigger: EnchantmentsTrigger::OnHit, nth: 0, chance_pct_per_level: 100.0, value_per_level: 12.0, value_unit: EnchantmentsValueUnit::PctHitDamage, radius_m: 0.0, target_hp_below_pct: 50.0, game_effect: &EFFECTS_NONE, drop_weight: 12, coop: "as sharpness", description: "+12% damage per level against wounded enemies (below half health)." };
pub const ENCHANTMENTS_LEECHING: EnchantmentsRow = EnchantmentsRow { id: "leeching", dungeons_name: "Leeching", slot: EnchantmentsSlot::Weapon, trigger: EnchantmentsTrigger::OnKill, nth: 0, chance_pct_per_level: 100.0, value_per_level: 2.0, value_unit: EnchantmentsValueUnit::PctPlayerMaxHp, radius_m: 0.0, target_hp_below_pct: 100.0, game_effect: &EFFECTS_NONE, drop_weight: 12, coop: "heals only the player who killed", description: "Kills heal 2% of your max HP per level." };
pub const ENCHANTMENTS_SWIRLING: EnchantmentsRow = EnchantmentsRow { id: "swirling", dungeons_name: "Swirling", slot: EnchantmentsSlot::Weapon, trigger: EnchantmentsTrigger::EveryNthHit, nth: 3, chance_pct_per_level: 100.0, value_per_level: 20.0, value_unit: EnchantmentsValueUnit::PctHitDamage, radius_m: 3.0, target_hp_below_pct: 100.0, game_effect: &EFFECTS_NONE, drop_weight: 10, coop: "as sharpness", description: "Every third hit also hits enemies around you for 20% per level." };
pub const ENCHANTMENTS_FIRE_ASPECT: EnchantmentsRow = EnchantmentsRow { id: "fire_aspect", dungeons_name: "Fire Aspect", slot: EnchantmentsSlot::Weapon, trigger: EnchantmentsTrigger::OnHit, nth: 0, chance_pct_per_level: 10.0, value_per_level: 0.0, value_unit: EnchantmentsValueUnit::None, radius_m: 0.0, target_hp_below_pct: 100.0, game_effect: &EFFECTS_SP_HP_BURN, drop_weight: 10, coop: "SpEffect applied to the enemy with sync on", description: "10% chance per level to set the enemy on fire." };
pub const ENCHANTMENTS_ECHO: EnchantmentsRow = EnchantmentsRow { id: "echo", dungeons_name: "Echo", slot: EnchantmentsSlot::Weapon, trigger: EnchantmentsTrigger::OnHit, nth: 0, chance_pct_per_level: 8.0, value_per_level: 100.0, value_unit: EnchantmentsValueUnit::PctHitDamage, radius_m: 0.0, target_hp_below_pct: 100.0, game_effect: &EFFECTS_NONE, drop_weight: 8, coop: "as sharpness", description: "8% chance per level for a hit to land twice." };
pub const ENCHANTMENTS_THORNS: EnchantmentsRow = EnchantmentsRow { id: "thorns", dungeons_name: "Thorns", slot: EnchantmentsSlot::Armor, trigger: EnchantmentsTrigger::OnHurt, nth: 0, chance_pct_per_level: 100.0, value_per_level: 12.0, value_unit: EnchantmentsValueUnit::PctHitDamage, radius_m: 0.0, target_hp_below_pct: 100.0, game_effect: &EFFECTS_NONE, drop_weight: 12, coop: "as sharpness", description: "Attackers take 12% per level of the damage they deal you." };
pub const ENCHANTMENTS_COOL_DOWN: EnchantmentsRow = EnchantmentsRow { id: "cool_down", dungeons_name: "Cool Down", slot: EnchantmentsSlot::Armor, trigger: EnchantmentsTrigger::Passive, nth: 0, chance_pct_per_level: 100.0, value_per_level: 8.0, value_unit: EnchantmentsValueUnit::PctCooldown, radius_m: 0.0, target_hp_below_pct: 100.0, game_effect: &EFFECTS_NONE, drop_weight: 10, coop: "local only", description: "Artifact cooldowns 8% shorter per level." };
pub const ENCHANTMENTS_HEALTH_SYNERGY: EnchantmentsRow = EnchantmentsRow { id: "health_synergy", dungeons_name: "Health Synergy", slot: EnchantmentsSlot::Armor, trigger: EnchantmentsTrigger::OnArtifactUse, nth: 0, chance_pct_per_level: 100.0, value_per_level: 2.0, value_unit: EnchantmentsValueUnit::PctPlayerMaxHp, radius_m: 0.0, target_hp_below_pct: 100.0, game_effect: &EFFECTS_NONE, drop_weight: 10, coop: "local only", description: "Using an artifact heals 2% of your max HP per level." };
pub static ENCHANTMENTS: &[&EnchantmentsRow] = &[&ENCHANTMENTS_SHARPNESS, &ENCHANTMENTS_COMMITTED, &ENCHANTMENTS_LEECHING, &ENCHANTMENTS_SWIRLING, &ENCHANTMENTS_FIRE_ASPECT, &ENCHANTMENTS_ECHO, &ENCHANTMENTS_THORNS, &ENCHANTMENTS_COOL_DOWN, &ENCHANTMENTS_HEALTH_SYNERGY];

// ---- loot: When an enemy killed by the local player drops Dungeons loot. A drop is a coloured beam at the body; walk into it to pick it up. Enemy strength is read from max HP because Elden Ring has no elite flag the mod can read.
#[derive(Debug)]
pub struct LootRow {
    pub id: &'static str,
    pub source: &'static str,
    pub first_kill_only: bool,
    pub min_enemy_max_hp: i32,
    pub max_enemy_max_hp: i32,
    pub chance_pct: f32,
    pub min_rarity: &'static RarityRow,
    pub w_artifact: i32,
    pub w_weapon_enchant: i32,
    pub w_armor_enchant: i32,
    pub pickup_radius_m: f32,
    pub beam_ttl_s: f32,
}
pub const LOOT_FIRST_KILL: LootRow = LootRow { id: "first_kill", source: "The first enemy a character kills with the mod on (the first-minute moment)", first_kill_only: true, min_enemy_max_hp: 0, max_enemy_max_hp: 2147483647, chance_pct: 100.0, min_rarity: &RARITY_RARE, w_artifact: 1, w_weapon_enchant: 0, w_armor_enchant: 0, pickup_radius_m: 1.6, beam_ttl_s: 600.0 };
pub const LOOT_ENEMY: LootRow = LootRow { id: "enemy", source: "Ordinary enemy", first_kill_only: false, min_enemy_max_hp: 0, max_enemy_max_hp: 1499, chance_pct: 8.0, min_rarity: &RARITY_COMMON, w_artifact: 35, w_weapon_enchant: 40, w_armor_enchant: 25, pickup_radius_m: 1.6, beam_ttl_s: 180.0 };
pub const LOOT_STRONG_ENEMY: LootRow = LootRow { id: "strong_enemy", source: "Knights, trolls, field elites", first_kill_only: false, min_enemy_max_hp: 1500, max_enemy_max_hp: 7999, chance_pct: 35.0, min_rarity: &RARITY_COMMON, w_artifact: 35, w_weapon_enchant: 40, w_armor_enchant: 25, pickup_radius_m: 1.6, beam_ttl_s: 300.0 };
pub const LOOT_BOSS: LootRow = LootRow { id: "boss", source: "Bosses and field bosses", first_kill_only: false, min_enemy_max_hp: 8000, max_enemy_max_hp: 2147483647, chance_pct: 100.0, min_rarity: &RARITY_RARE, w_artifact: 50, w_weapon_enchant: 30, w_armor_enchant: 20, pickup_radius_m: 2.0, beam_ttl_s: 900.0 };
pub static LOOT: &[&LootRow] = &[&LOOT_FIRST_KILL, &LOOT_ENEMY, &LOOT_STRONG_ENEMY, &LOOT_BOSS];

// ---- hooks: Every place the DLL touches the running game. Elden Ring 1.17.1 (exe 2.7.1.0) only: fromsoftware-rs main @59fbd3b ships RVAs for that build. Nothing is patched on disk; ModEngine2 loads the DLL.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum HooksAccess { Read, Write, Call, Draw, Os }
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum HooksTaskGroup { FrameBegin, ChrInsPostPhysics, DrawParamUpdate, Boot, Overlay, Any }
#[derive(Debug)]
pub struct HooksRow {
    pub id: &'static str,
    pub game_object: &'static str,
    pub access: HooksAccess,
    pub task_group: HooksTaskGroup,
    pub crate_api: &'static str,
    pub purpose: &'static str,
}
pub const HOOKS_GAME_VERSION: HooksRow = HooksRow { id: "game_version", game_object: "eldenring.exe version resource", access: HooksAccess::Read, task_group: HooksTaskGroup::Boot, crate_api: "eldenring git main @59fbd3b (Ww2710 = exe 2.7.1.0, Jp2711); crates.io 0.14.0 only knows 2.6.2.0, so the git pin is required", purpose: "Check the exe version ourselves first; on any other build log it and stay inactive instead of panicking" };
pub const HOOKS_TASK_RUNNER: HooksRow = HooksRow { id: "task_runner", game_object: "CSTask", access: HooksAccess::Call, task_group: HooksTaskGroup::Boot, crate_api: "CSTaskImp::wait_for_instance + run_recurring", purpose: "Run the mod's per-frame tasks inside the game loop" };
pub const HOOKS_MAIN_PLAYER: HooksRow = HooksRow { id: "main_player", game_object: "WorldChrMan.main_player (PlayerIns)", access: HooksAccess::Read, task_group: HooksTaskGroup::Any, crate_api: "WorldChrMan::instance", purpose: "Player position, orientation, handle, game data" };
pub const HOOKS_PLAYER_GAME_DATA: HooksRow = HooksRow { id: "player_game_data", game_object: "PlayerIns.player_game_data", access: HooksAccess::Write, task_group: HooksTaskGroup::FrameBegin, crate_api: "PlayerGameData.current_fp / current_hp / character_name / equipment.chr_asm", purpose: "FP cost of artifacts, heals, equipped gear handles, save key" };
pub const HOOKS_FOLLOW_CAMERA: HooksRow = HooksRow { id: "follow_camera", game_object: "WorldChrMan.chr_cam (ChrCam.pers_cam.matrix)", access: HooksAccess::Write, task_group: HooksTaskGroup::FrameBegin, crate_api: "ChrCam", purpose: "Pin the follow camera's yaw to the Dungeons yaw so movement is screen-relative" };
pub const HOOKS_RENDER_CAMERA: HooksRow = HooksRow { id: "render_camera", game_object: "CSCamera.pers_cam_1 (CSCam.matrix, fov)", access: HooksAccess::Write, task_group: HooksTaskGroup::DrawParamUpdate, crate_api: "CSCamera::instance_mut", purpose: "Draw the world from the Dungeons camera" };
pub const HOOKS_PLAYER_ORIENTATION: HooksRow = HooksRow { id: "player_orientation", game_object: "PlayerIns.chr_ins.modules.physics.orientation", access: HooksAccess::Write, task_group: HooksTaskGroup::ChrInsPostPhysics, crate_api: "CSChrPhysicsModule.orientation", purpose: "Turn the character toward the cursor when attacking" };
pub const HOOKS_PHYS_RAYCAST: HooksRow = HooksRow { id: "phys_raycast", game_object: "CSHavokMan.phys_world", access: HooksAccess::Call, task_group: HooksTaskGroup::DrawParamUpdate, crate_api: "CSPhysWorld::cast_ray", purpose: "Cursor ground point and ceiling avoidance" };
pub const HOOKS_BULLET_SPAWN: HooksRow = HooksRow { id: "bullet_spawn", game_object: "CSBulletManager", access: HooksAccess::Call, task_group: HooksTaskGroup::FrameBegin, crate_api: "CSBulletManager::spawn_bullet (BulletSpawnData mirrored with the same layout)", purpose: "Artifacts that throw, call or burst" };
pub const HOOKS_SPEFFECT_APPLY: HooksRow = HooksRow { id: "speffect_apply", game_object: "ChrIns", access: HooksAccess::Call, task_group: HooksTaskGroup::FrameBegin, crate_api: "ChrInsExt::apply_speffect", purpose: "Buff artifacts and Fire Aspect" };
pub const HOOKS_ENEMY_LIST: HooksRow = HooksRow { id: "enemy_list", game_object: "WorldChrMan.chr_inses_by_distance", access: HooksAccess::Read, task_group: HooksTaskGroup::ChrInsPostPhysics, crate_api: "ChrInsDistanceEntry", purpose: "Find enemies the player hit or killed, and enemies near the player" };
pub const HOOKS_ENEMY_HP: HooksRow = HooksRow { id: "enemy_hp", game_object: "ChrIns.modules.data.hp / max_hp, ChrIns.last_hit_by", access: HooksAccess::Write, task_group: HooksTaskGroup::ChrInsPostPhysics, crate_api: "CSChrDataModule", purpose: "Detect hits and kills by the player; apply enchantment damage" };
pub const HOOKS_DEBUG_DRAW: HooksRow = HooksRow { id: "debug_draw", game_object: "RendMan.debug_ez_draw", access: HooksAccess::Draw, task_group: HooksTaskGroup::ChrInsPostPhysics, crate_api: "CSEzDraw::draw_capsule", purpose: "Loot beams in the world" };
pub const HOOKS_INPUT_KEYS: HooksRow = HooksRow { id: "input_keys", game_object: "Win32 keyboard state", access: HooksAccess::Os, task_group: HooksTaskGroup::Any, crate_api: "GetAsyncKeyState", purpose: "Mod keys from the controls sheet, only while the game window is focused" };
pub const HOOKS_MOUSE_CURSOR: HooksRow = HooksRow { id: "mouse_cursor", game_object: "Win32 cursor + game window", access: HooksAccess::Os, task_group: HooksTaskGroup::Any, crate_api: "GetCursorPos / ScreenToClient / GetClientRect", purpose: "Aim point under the mouse" };
pub const HOOKS_ITEM_NAMES: HooksRow = HooksRow { id: "item_names", game_object: "MsgRepository (GoodsName)", access: HooksAccess::Read, task_group: HooksTaskGroup::Any, crate_api: "fallback: dungeons_name only", purpose: "Show the Elden Ring item each artifact is made from" };
pub const HOOKS_OVERLAY: HooksRow = HooksRow { id: "overlay", game_object: "D3D12 swap chain", access: HooksAccess::Draw, task_group: HooksTaskGroup::Overlay, crate_api: "hudhook (ImGui)", purpose: "Hotbar, satchel, cursor, toasts, gear panel" };
pub const HOOKS_SAVE_FILE: HooksRow = HooksRow { id: "save_file", game_object: "%APPDATA%/LandsBetweenDungeons/<character name>.json", access: HooksAccess::Os, task_group: HooksTaskGroup::Any, crate_api: "std::fs + serde_json", purpose: "Owned artifacts, hotbar, enchantments per character; never touches ER0000.sl2 / .co2" };
pub static HOOKS: &[&HooksRow] = &[&HOOKS_GAME_VERSION, &HOOKS_TASK_RUNNER, &HOOKS_MAIN_PLAYER, &HOOKS_PLAYER_GAME_DATA, &HOOKS_FOLLOW_CAMERA, &HOOKS_RENDER_CAMERA, &HOOKS_PLAYER_ORIENTATION, &HOOKS_PHYS_RAYCAST, &HOOKS_BULLET_SPAWN, &HOOKS_SPEFFECT_APPLY, &HOOKS_ENEMY_LIST, &HOOKS_ENEMY_HP, &HOOKS_DEBUG_DRAW, &HOOKS_INPUT_KEYS, &HOOKS_MOUSE_CURSOR, &HOOKS_ITEM_NAMES, &HOOKS_OVERLAY, &HOOKS_SAVE_FILE];

// ---- ui: Everything the mod draws. Overlay rows are ImGui windows drawn by hudhook; the beam is drawn into the world.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UiKind { Overlay, World }
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UiAnchor { BottomCenter, TopCenter, RightCenter, Cursor, World }
#[derive(Debug)]
pub struct UiRow {
    pub id: &'static str,
    pub kind: UiKind,
    pub anchor: UiAnchor,
    pub offset_x_px: i32,
    pub offset_y_px: i32,
    pub shown_when: &'static str,
    pub hook: &'static HooksRow,
    pub contents: &'static str,
}
pub const UI_HOTBAR: UiRow = UiRow { id: "hotbar", kind: UiKind::Overlay, anchor: UiAnchor::BottomCenter, offset_x_px: 0, offset_y_px: -120, shown_when: "Dungeons view on", hook: &HOOKS_OVERLAY, contents: "3 slots: key, artifact name, Elden Ring item, cooldown sweep, FP cost" };
pub const UI_SATCHEL: UiRow = UiRow { id: "satchel", kind: UiKind::Overlay, anchor: UiAnchor::RightCenter, offset_x_px: -40, offset_y_px: 0, shown_when: "artifact_menu toggled", hook: &HOOKS_OVERLAY, contents: "Owned artifacts; click one then a slot to equip it; shows gear enchantments" };
pub const UI_TOAST: UiRow = UiRow { id: "toast", kind: UiKind::Overlay, anchor: UiAnchor::TopCenter, offset_x_px: 0, offset_y_px: 90, shown_when: "4 s after a pickup", hook: &HOOKS_OVERLAY, contents: "Rarity-coloured line: 'Rare  Sharpness II  on Longsword'" };
pub const UI_RETICLE: UiRow = UiRow { id: "reticle", kind: UiKind::Overlay, anchor: UiAnchor::Cursor, offset_x_px: 0, offset_y_px: 0, shown_when: "Dungeons view on", hook: &HOOKS_OVERLAY, contents: "Ring where the next attack or artifact aims" };
pub const UI_LOOT_BEAM: UiRow = UiRow { id: "loot_beam", kind: UiKind::World, anchor: UiAnchor::World, offset_x_px: 0, offset_y_px: 0, shown_when: "a drop is waiting", hook: &HOOKS_DEBUG_DRAW, contents: "Vertical capsule in the rarity colour at the body" };
pub static UI: &[&UiRow] = &[&UI_HOTBAR, &UI_SATCHEL, &UI_TOAST, &UI_RETICLE, &UI_LOOT_BEAM];

